export function assembleCharter(state) {
    const { tier } = state
    if (tier === 'micro') return assembleMicroCharter(state)
    if (tier === 'sprint') return assembleSprintCharter(state)
    return assembleFullCharter(state)
}

function assembleFullCharter(s) {
    const allCleared = s.gate && Object.values(s.gate).every(Boolean)
    const accessLabel = { wcag21aa: 'WCAG 2.1 AA', wcag22aa: 'WCAG 2.2 AA', wcag21aaa: 'WCAG 2.1 AAA' }[s.accessibility] || '___'

    return [
        'CHARTERED DESIGN — DESIGN CHARTER',
        'SYS.PHASE_0 // INTAKE_AND_ACCOUNTABILITY',
        '─'.repeat(40),
        '',
        `PROJECT: ${s.projectName || '___'}`,
        `PRODUCT: ${s.product || '___'}`,
        `TIMELINE: ${s.timeline || '___'}`,
        `DATE: ${s.date || '___'}`,
        'TIER: FULL CHARTER',
        '',
        '═'.repeat(40),
        'EXPERIENCE DECISION OWNER',
        '═'.repeat(40),
        '',
        `EDO: ${s.edoName || '___'}`,
        `ROLE: ${s.edoRole || '___'}`,
        `ESCALATION: ${s.escalation || '___'}`,
        '',
        'ENFORCEMENT MODEL:',
        `${s.enforcement?.authority ? '✓' : '○'} EDO AUTHORITY`,
        `${s.enforcement?.dod ? '✓' : '○'} DEFINITION OF DONE`,
        `${s.enforcement?.sprint ? '✓' : '○'} SPRINT PLANNING GATE`,
        '',
        '═'.repeat(40),
        'ACCOUNTABILITY MAP',
        '═'.repeat(40),
        '',
        'USERS',
        `> PRIMARY POPULATION: ${s.users || '___'}`,
        `> AT RISK IF FAILS: ${s.atRisk || '___'}`,
        `> VOICE MECHANISM: ${s.voiceMechanism || '___'}`,
        '',
        'BUSINESS',
        `> METRIC + OWNER: ${s.businessMetric || '___'}`,
        `> ESCALATION: ${s.businessEscalation || '___'}`,
        '',
        'COMPLIANCE / LEGAL',
        `> STANDARDS: ${s.compliance || '___'}`,
        `> REVIEWER: ${s.complianceReviewer || '___'}`,
        '',
        'OPERATIONS',
        `> POST-LAUNCH OWNER: ${s.operations || '___'}`,
        `> PRE-SHIP NOTIFICATION: ${s.opsNotify || '___'}`,
        '',
        '═'.repeat(40),
        'ACCESSIBILITY STANDARD',
        '═'.repeat(40),
        '',
        `STANDARD: ${accessLabel}`,
        `KNOWN ACCESS NEEDS: ${s.accessNeeds || '___'}`,
        `TESTING METHOD: ${s.testingMethod || '___'}`,
        '',
        '═'.repeat(40),
        'CONSTRAINTS',
        '═'.repeat(40),
        '',
        'USER',
        s.userConstraints || '___',
        '',
        'BUSINESS',
        s.businessConstraints || '___',
        '',
        'TECHNICAL',
        s.technicalConstraints || '___',
        '',
        'OPERATIONAL',
        s.operationalConstraints || '___',
        '',
        '═'.repeat(40),
        'SUCCESS + FAILURE',
        '═'.repeat(40),
        '',
        'SUCCESS',
        `> PRIMARY METRIC: ${s.primaryMetric || '___'}`,
        `> LEADING INDICATOR: ${s.leadingIndicator || '___'}`,
        `> TIMEFRAME: ${s.timeframe || '___'}`,
        `> REVIEWER: ${s.metricReviewer || '___'}`,
        '',
        'FAILURE CONDITIONS',
        `✗ CRITICAL FAILURE: ${s.criticalFailure || '___'}`,
        `✗ USER HARM: ${s.userHarm || '___'}`,
        `✗ ORGANIZATIONAL RISK: ${s.orgRisk || '___'}`,
        `✗ SIGNAL WE WERE WRONG: ${s.wrongSignal || '___'}`,
        '',
        '═'.repeat(40),
        'GATE TO PROCEED',
        '═'.repeat(40),
        '',
        `${s.gate?.edo ? '✓' : '○'} EDO CONFIRMED`,
        `${s.gate?.accountability ? '✓' : '○'} ACCOUNTABILITY MAP COMPLETE`,
        `${s.gate?.accessibility ? '✓' : '○'} ACCESSIBILITY DECLARED`,
        `${s.gate?.constraints ? '✓' : '○'} CONSTRAINTS ADDRESSED`,
        `${s.gate?.metrics ? '✓' : '○'} METRICS + FAILURE NAMED`,
        '',
        `GATE STATUS: ${allCleared ? 'CLEARED' : 'NOT CLEARED'}`,
        '',
        '─'.repeat(40),
        '// CHARTERED_DESIGN // DESIGN_CHARTER_V1',
        '// AI GENERATES CANDIDATES.',
        '// HUMANS OWN THE CONSEQUENCES.',
    ].join('\n')
}

function assembleSprintCharter(s) {
    const allCleared = s.gate && Object.values(s.gate).every(Boolean)
    const accessLabel = { wcag21aa: 'WCAG 2.1 AA', wcag22aa: 'WCAG 2.2 AA', wcag21aaa: 'WCAG 2.1 AAA' }[s.accessibility] || '___'

    return [
        'CHARTERED DESIGN — SPRINT CHARTER',
        'SYS.TIER_B // 30_MINUTES',
        '─'.repeat(40),
        '',
        `PROJECT: ${s.projectName || '___'}`,
        `PRODUCT: ${s.product || '___'}`,
        `TIMELINE: ${s.timeline || '___'}`,
        `DATE: ${s.date || '___'}`,
        'TIER: SPRINT CHARTER',
        '',
        '═'.repeat(40),
        'EXPERIENCE DECISION OWNER',
        '═'.repeat(40),
        '',
        `EDO: ${s.edoName || '___'}`,
        `ROLE: ${s.edoRole || '___'}`,
        `ESCALATION: ${s.escalation || '___'}`,
        '',
        'ENFORCEMENT MODEL:',
        `${s.enforcement?.authority ? '✓' : '○'} EDO AUTHORITY`,
        `${s.enforcement?.dod ? '✓' : '○'} DEFINITION OF DONE`,
        `${s.enforcement?.sprint ? '✓' : '○'} SPRINT PLANNING GATE`,
        '',
        '═'.repeat(40),
        'ACCOUNTABILITY MAP',
        '═'.repeat(40),
        '',
        'USERS',
        `> PRIMARY POPULATION: ${s.users || '___'}`,
        `> AT RISK IF FAILS: ${s.atRisk || '___'}`,
        `> VOICE MECHANISM: ${s.voiceMechanism || '___'}`,
        '',
        'BUSINESS',
        `> METRIC + OWNER: ${s.businessMetric || '___'}`,
        `> ESCALATION: ${s.businessEscalation || '___'}`,
        '',
        '═'.repeat(40),
        'ACCESSIBILITY STANDARD',
        '═'.repeat(40),
        '',
        `STANDARD: ${accessLabel}`,
        `TESTING METHOD: ${s.testingMethod || '___'}`,
        '',
        '═'.repeat(40),
        'CONSTRAINTS',
        '═'.repeat(40),
        '',
        'USER',
        s.userConstraints || '___',
        '',
        'BUSINESS',
        s.businessConstraints || '___',
        '',
        'TECHNICAL',
        s.technicalConstraints || '___',
        '',
        '═'.repeat(40),
        'SUCCESS + FAILURE',
        '═'.repeat(40),
        '',
        'SUCCESS',
        `> PRIMARY METRIC: ${s.primaryMetric || '___'}`,
        `> TIMEFRAME: ${s.timeframe || '___'}`,
        `> REVIEWER: ${s.metricReviewer || '___'}`,
        '',
        'FAILURE CONDITIONS',
        `✗ CRITICAL FAILURE MODE: ${s.criticalFailure || '___'}`,
        `✗ USER HARM SCENARIO: ${s.userHarm || '___'}`,
        `✗ SIGNAL WE WERE WRONG: ${s.wrongSignal || '___'}`,
        '',
        '═'.repeat(40),
        'GATE TO PROCEED',
        '═'.repeat(40),
        '',
        `${s.gate?.edo ? '✓' : '○'} EDO CONFIRMED`,
        `${s.gate?.accountability ? '✓' : '○'} ACCOUNTABILITY MAP COMPLETE`,
        `${s.gate?.accessibility ? '✓' : '○'} ACCESSIBILITY DECLARED`,
        `${s.gate?.constraints ? '✓' : '○'} CONSTRAINTS ADDRESSED`,
        `${s.gate?.metrics ? '✓' : '○'} METRICS + FAILURE NAMED`,
        '',
        `GATE STATUS: ${allCleared ? 'CLEARED' : 'NOT CLEARED'}`,
        '',
        '─'.repeat(40),
        '// CHARTERED_DESIGN // SPRINT_CHARTER_V1',
        '// AI GENERATES CANDIDATES.',
        '// HUMANS OWN THE CONSEQUENCES.',
    ].join('\n')
}

function assembleMicroCharter(s) {
    const accessLabel = s.accessibility === 'wcag21aa' ? 'WCAG 2.1 AA'
        : s.accessibility === 'wcag22aa' ? 'WCAG 2.2 AA'
            : s.accessibility === 'na' ? `N/A — ${s.naReason || '___'}`
                : '___'

    return [
        'CHARTERED DESIGN — MICRO CHARTER',
        'SYS.TIER_C // 90_SECONDS',
        '─'.repeat(40),
        '',
        `OWNER: ${s.edoName || '___'}`,
        `CHANGE: ${s.what || '___'}`,
        `CONSTRAINT: ${s.constraint || '___'}`,
        `SUCCESS SIGNAL: ${s.successSignal || '___'}`,
        `FAILURE SIGNAL: ${s.failureSignal || '___'}`,
        `ACCESSIBILITY: ${accessLabel}`,
        '',
        '─'.repeat(40),
        '// CHARTERED_DESIGN // MICRO_CHARTER_V1',
        '// AI GENERATES CANDIDATES.',
        '// HUMANS OWN THE CONSEQUENCES.',
    ].join('\n')
}
