export function assembleDecisionLog(s) {
    return [
        'CHARTERED DESIGN — DECISION LOG ENTRY',
        'SYS.PHASE_4 // PROTOTYPE_AND_DECIDE',
        '─'.repeat(40),
        '',
        `ID: ${s.id || 'DEC-___'}`,
        `TITLE: ${s.title || '___'}`,
        `OWNER: ${s.owner || '___'}`,
        `DATE: ${s.date || '___'}`,
        `STATUS: ${s.status?.toUpperCase() || '___'}`,
        `RISK: ${s.risk?.toUpperCase() || '___'}`,
        `AREA: ${s.area || '___'}`,
        '',
        '═'.repeat(40),
        'CONTEXT',
        '═'.repeat(40),
        s.context || '___',
        '',
        '═'.repeat(40),
        'CONSTRAINTS (NON-NEGOTIABLES)',
        '═'.repeat(40),
        s.constraints || '___',
        '',
        '═'.repeat(40),
        'OPTIONS CONSIDERED',
        '═'.repeat(40),
        `OPTION 1: ${s.option1 || '___'}`,
        `✗ REJECTED: ${s.option1rejected || '___'}`,
        '',
        `OPTION 2: ${s.option2 || '___'}`,
        `✗ REJECTED: ${s.option2rejected || '___'}`,
        '',
        ...(s.option3 ? [
            `OPTION 3: ${s.option3}`,
            `✗ REJECTED: ${s.option3rejected || '___'}`,
            '',
        ] : []),
        '═'.repeat(40),
        'DECISION',
        '═'.repeat(40),
        `> CHOSEN: ${s.chosen || '___'}`,
        '',
        'RATIONALE:',
        s.rationale || '___',
        '',
        '═'.repeat(40),
        'RISK + MITIGATION',
        '═'.repeat(40),
        'RISKS:',
        s.risks || '___',
        '',
        'MITIGATIONS:',
        s.mitigations || '___',
        '',
        '═'.repeat(40),
        'WHAT WOULD CHANGE OUR MIND',
        '═'.repeat(40),
        s.whatWouldChangeOurMind || '___',
        '',
        '═'.repeat(40),
        'FOLLOW-UP',
        '═'.repeat(40),
        `DATE: ${s.followUpDate || '___'}`,
        `REVIEWER: ${s.followUpReviewer || '___'}`,
        '',
        '─'.repeat(40),
        '// CHARTERED_DESIGN // DECISION_LOG_V1',
        '// AI GENERATES CANDIDATES.',
        '// HUMANS OWN THE CONSEQUENCES.',
    ].join('\n')
}

export function assembleFullDecisionLog(entries) {
    const dateStr = new Date().toISOString().split('T')[0]

    const index = entries.map((e, i) =>
        `${String(i + 1).padStart(2, '0')}. ${e.id || 'DEC-???'} — ${e.title || '___'} [${e.status?.toUpperCase() || '___'}] [${e.risk?.toUpperCase() || '___'} RISK]`
    ).join('\n')

    const fullEntries = entries.map(e => [
        '─'.repeat(40),
        `${e.id || 'DEC-___'} — ${e.title || '___'}`,
        '─'.repeat(40),
        '',
        `OWNER: ${e.owner || '___'}`,
        `DATE: ${e.date || '___'}`,
        `STATUS: ${e.status?.toUpperCase() || '___'}`,
        `RISK: ${e.risk?.toUpperCase() || '___'}`,
        `AREA: ${e.area || '___'}`,
        '',
        'CONTEXT:',
        e.context || '___',
        '',
        'CONSTRAINTS:',
        e.constraints || '___',
        '',
        'OPTIONS CONSIDERED:',
        `OPTION 1: ${e.option1 || '___'}`,
        `✗ REJECTED: ${e.option1rejected || '___'}`,
        '',
        `OPTION 2: ${e.option2 || '___'}`,
        `✗ REJECTED: ${e.option2rejected || '___'}`,
        '',
        ...(e.option3 ? [
            `OPTION 3: ${e.option3}`,
            `✗ REJECTED: ${e.option3rejected || '___'}`,
            '',
        ] : []),
        'DECISION:',
        `> CHOSEN: ${e.chosen || '___'}`,
        '',
        'RATIONALE:',
        e.rationale || '___',
        '',
        'RISKS:',
        e.risks || '___',
        '',
        'MITIGATIONS:',
        e.mitigations || '___',
        '',
        '⚡ WHAT WOULD CHANGE OUR MIND:',
        e.whatWouldChangeOurMind || '___',
        '',
        `FOLLOW-UP DATE: ${e.followUpDate || '___'}`,
        `REVIEWER: ${e.followUpReviewer || '___'}`,
    ].join('\n')).join('\n\n')

    return [
        'CHARTERED DESIGN — FULL DECISION LOG',
        'SYS.PHASE_4 // ALL_ENTRIES',
        `EXPORTED: ${dateStr}`,
        `TOTAL ENTRIES: ${entries.length}`,
        '═'.repeat(40),
        '',
        '═'.repeat(40),
        'DECISION INDEX',
        '═'.repeat(40),
        index,
        '',
        '═'.repeat(40),
        'FULL ENTRIES',
        '═'.repeat(40),
        '',
        fullEntries,
        '',
        '═'.repeat(40),
        '// CHARTERED_DESIGN // DECISION_LOG_FULL_EXPORT',
        '// AI GENERATES CANDIDATES.',
        '// HUMANS OWN THE CONSEQUENCES.',
    ].join('\n')
}
